# This is the config file of Jekyll

theme: minima
title: "Hansen 的博客"
description: "计算机科学的狂热分子"

# Navigate Links
header_pages:
  - home.md
  - about.md

# Author MetaData
author:
  name: 郑翰成
  email: "hansenzh11@hotmail.com"
