
title: "Hansen 的博客"
description: "喜欢计算机技术，做一名志向远大的软件工程师。"

author: 郑翰成

email: "hansenzh11@hotmail.com"

header_pages:
  - index.md
  - about.md

minima:
  skin: dark
  date_format: "%Y-%m-%d"

theme: minima
