
title: "Hansen Blog"
description: "Love Computer Science and Data Science"

author: Hancheng Zheng

email: "hansenzh11@hotmail.com"

header_pages:
  - index.md
  - about.md

minima:
  skin: dark
  date_format: "%Y-%m-%d"

show_excerpts: true

theme: minima
