
title: "Hansen‘s Blog"
description: >
  Love Computer Science and Data Science. 
  好奇世界的打开者，不断探索的技术宅

author: Hancheng Zheng

email: "hansenzh11@hotmail.com"

header_pages:
  - index.md
  - about.md

minima:
  skin: dark
  date_format: "%Y-%m-%d"

show_excerpts: true

theme: minima
